#!/usr/bin/env bash

echo -e "\e[32m[+] Starting password genertor\e[0m"
sleep 2
echo -e "\e[34m [+] for Default Press ENTER \e[0m"
read -p "Enter length of the password [default : 12 ] : " pass_length

pass_length=${pass_length:-12}



echo ${pass_length}

echo -e "include\n1.Letter\t2.Number\t3.Special charter"
read -p "Enter eg..123 , 23 ,12 [default 123 ]:" options

options=${options:-123}
if [[ ${options} =~ ^[1-3]*$ ]];then 
	echo  "Valid options"
else 
	echo "Invalid"
	exit 1
fi




char=""


options_len=${#options}
for((i=0;i<options_len;i++));do
	s_option=${options:i:1}
	if [ ${s_option} = "1" ]; then
		 
	      	char+="a-zA-Z"	
	
	fi 
	if [ ${s_option} = "2" ]; then
		
		char+="0-9"
	
	fi
	
	if [ ${s_option} = "3" ]; then
	
		char+="!@#$%^&*()"

	
	fi 
	
done

password=$(tr -dc "$char" < /dev/urandom | head -c "$pass_length")
echo -e "\e[32m your passowrd is : ${password} \e[0m"

read -p "Copy to clipboard : n/y  : " copy


if [[ ${copy} =~ ^[yY]$ ]]; then
	read -p "time after delete for clipboard in min (min 1m) :" d_time
	d_time=${d_time:-1m}
	echo -n "${password}"|xclip -selection clipboard
	echo -e "\e[32m copied to clipboard \e[0m"
	sleep "$d_time"
	echo -n "" | xclip -selection clipboard

	exit 1
else 
	exit 1
fi



